parameters:
#    zing_core_access.example.class: Zing\Core\AccessBundle\Example

services:
#    zing_core_access.example:
#        class: %zing_core_access.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
