parameters:
#    zing_core_admin.example.class: Zing\Core\AdminBundle\Example

services:
#    zing_core_admin.example:
#        class: %zing_core_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
