parameters:
#    zing_core_analytics.example.class: Zing\Core\AnalyticsBundle\Example

services:
#    zing_core_analytics.example:
#        class: %zing_core_analytics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
