parameters:
#    zing_core_front.example.class: Zing\Core\FrontBundle\Example

services:
#    zing_core_front.example:
#        class: %zing_core_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
