parameters:
#    zing_core_component.example.class: Zing\Core\ComponentBundle\Example

services:
#    zing_core_component.example:
#        class: %zing_core_component.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
